name = "fileio-uploader"
account_id = "eabf79add01949143764d93a6f97d54f"
workers_dev = true
compatibility_date = "2025-03-23"

# Define the worker script entry point
main = "worker.js"

# Serve static assets (index.html)
[site]
bucket = "./"
entry-point = "."
