name = "fileio-uploader"
type = "javascript"

account_id = "eabf79add01949143764d93a6f97d54f"
workers_dev = true

[build]
command = ""

[site]
bucket = "./"
entry-point = "."

# Remove this if you're not using a custom domain
#[env.production]
#route = "yourdomain.com/*"
#zone_id = "your-cloudflare-zone-id"
