name = "fileio-uploader"
account_id = "your-cloudflare-account-id"
workers_dev = true
compatibility_date = "2025-03-23"

# Define the worker entry script
main = "worker.js"

[site]
bucket = "./"
entry-point = "."

# Uncomment only if you have a custom domain
#[env.production]
#route = "yourdomain.com/*"
#zone_id = "your-cloudflare-zone-id"
